### PR TITLE
Changes for solo5 hvt (previously ukvm) and tests

### LINKED ISSUE #13: solo5 hvt (ukvm) not working
Process segfaulting here:
```
            |      ___|
  __|  _ \  |  _ \ __ \
\__ \ (   | | (   |  ) |
____/\___/ _|\___/____/
Solo5: Memory map: 512 MB addressable:
Solo5:   reserved @ (0x0 - 0xfffff)
Solo5:       text @ (0x100000 - 0x2f1367)
Solo5:     rodata @ (0x2f1368 - 0x339147)
Solo5:       data @ (0x339148 - 0x40dc77)
Solo5:       heap >= 0x40e000 < stack < 0x20000000
rump kernel bare metal bootstrap

Copyright (c) 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
    2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016
    The NetBSD Foundation, Inc.  All rights reserved.
Copyright (c) 1982, 1986, 1989, 1991, 1993
    The Regents of the University of California.  All rights reserved.

NetBSD 7.99.34 (RUMP-ROAST)
total memory = 253 MB
timecounter: Timecounters tick every 10.000 msec
timecounter: Timecounter "clockinterrupt" frequency 100 Hz quality 0
cpu0 at thinair0: rump virtual cpu
root file system type: rumpfs
kern.module.path=/stand/amd64/7.99.34/modules
mainbus0 (root)
timecounter: Timecounter "bmktc" frequency 1000000000 Hz quality 100
Solo5: trap: type=#PF ec=0x0 rip=0x2f1124 rsp=0x41ff50 rflags=0x10006
Solo5: trap: cr2=0x28
Solo5: ABORT: cpu_x86_64.c:171: Fatal trap
```

Backtrace obtained from a core dump.
```
[New process 1]
#0  __guard_setup () at /home/kollerr/research/nabla-base-build/rumprun/src-netbsd/lib/libc/misc/stack_protector.c:58
58	{
(gdb) bt
#0  __guard_setup () at /home/kollerr/research/nabla-base-build/rumprun/src-netbsd/lib/libc/misc/stack_protector.c:58
#1  0x00000000002f13cd in _libc_init () at /home/kollerr/research/nabla-base-build/rumprun/src-netbsd/lib/libc/misc/initfini.c:97
#2  0x00000000002c95d9 in runinit () at /home/kollerr/research/nabla-base-build/rumprun/lib/librumprun_base/netbsd_initfini.c:68
#3  _netbsd_userlevel_init () at /home/kollerr/research/nabla-base-build/rumprun/lib/librumprun_base/netbsd_initfini.c:114
#4  0x00000000002c900e in rumprun_boot (cmdline=0x11000 "") at /home/kollerr/research/nabla-base-build/rumprun/lib/librumprun_base/rumprun.c:105
#5  0x00000000002c8d26 in bmk_mainthread (cmdline=<optimized out>) at /home/kollerr/research/nabla-base-build/rumprun/lib/librumprun_base/main.c:64
#6  0x00000000001018a8 in bmk_cpu_sched_bouncer ()
#7  0x0000000000000000 in ?? ()
```

Things work before this solo5 commit: 150bfa98b6a1330725f999f548c4d3fa9f64018a
The reason is that this particular commit unmaps the first 64KBs (including the NULL page).

### PR DESCRIPTION
**Pull request by ricarkol**
This is mainly to fix #13 . The fix is to disable stack protection (more in the commit message).

On top of that it adds tests for hvt and makes sure that the settls function is not called in solo5.

The way to run the HVT tests is:
```
cd tests/
./buildtests.sh -p solo5_hvt
./runtests.sh hvt
```
Can't run this in travis as we need KVM for HVT.

### CODE REVIEW

File: build-rr.sh [hunk 1]
```diff
@@ -374,7 +374,7 @@ buildrump ()
 		TLSCFLAGS="-F CFLAGS=-DRR_USE_TLS"
 	else
 		CURLWP_METHOD=hypercall
-		TLSCFLAGS="-F CFLAGS=-D_PTHREAD_GETTCB_EXT=_lwp_get_tls_tcb"
+		TLSCFLAGS="-F CFLAGS=-D_PTHREAD_GETTCB_EXT=_lwp_get_tls_tcb -F CFLAGS=-fno-stack-protector"
```
Comment (lumjjb) [inline build-rr.sh:377]: This is on the dangerous side, what is the reason for this?

Comment (lumjjb) [reply build-rr.sh:377]: Copying conversation:
@ricarkol :
it uses TLS
and we don't support it
we are planning to add a set_tls function in solo5

@lumjjb: 

Let's add an issue for this.

**Review by lumjjb — APPROVED** [review]
LGTM. To open issue for future work for TLS workaround.
